### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by joppiesaus** [rdfriedl/block-script#1]
* You can run to flat land
* Frame-based updating, which means if you have a 30fps panel it will run 2 times slower and an 120fps panel it will run 2 times faster + will run slow if your PC can't handle it,
* No way of selecting a block (?)
* If you're fast enough, you can run into an unloaded chunk, which makes you clip into the ground until you jump when the chunk is loaded.

**Comment by rdfriedl** [comment]
thanks for the feed back

the map generator is just temporary i plan to add an editor some point in the future.
aside from that, those are all things i will have to add to my to-do list.

**Comment by joppiesaus** [comment]
Ok, thank you!
Good luck!
